### ISSUE TITLE
你那里跑通了吗

### ISSUE THREAD

**Issue by Gethin0321** [363182860/layerAdmin-permission#1]

**Comment by donfisher** [comment]
可以使用的，你那边有什么问题？

**Comment by Gethin0321** [comment]
1,迁移文件 ( \database\migrations\2018_03_26_061335_create_clients_table.php ) 表名为 clients,
模型文件(\app\Client.php)那里     protected $table = 'Clients';

2, Permissions表迁移没有status字段

暂时发现这些
